site_name: HID Tech Pubs Style Guide
site_url: https://example.com/
theme:
  name: material
  logo: assets/tech-pubs-logo.svg

  # features:
  #  - navigation.tabs
  #  - navigation.sections
  #  - toc.integrate
  #  - navigation.top
  #  - search.suggest
  #  - search.highlight
  #  - content.tabs.link
  #  - content.code.annotation
  #  - content.code.copy

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.path
