site_name: HID Tech Pubs Style Guide
site_url: https://example.com/
theme:
  name: material
  logo: assets/images/tech-pubs-logo.svg
  favicon: assets/images/favicon.ico

  # features:
  #  - navigation.tabs
  #  - navigation.sections
  #  - toc.integrate
  #  - navigation.top
  #  - search.suggest
  #  - search.highlight
  #  - content.tabs.link
  #  - content.code.annotation
  #  - content.code.copy

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    # - navigation.tabs
    - navigation.path

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - About: "a-word-about-hid-tech-docs.md"
  - Voice and tone: "voice-and-tone.md"
  - Accessibility: "accessibility.md"
